// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOB_bgsxTWJKQ1sL4s-Ui-RgN4M4qvYlM',
    appId: '1:686400914700:web:e4104ab8fdb695a96cf529',
    messagingSenderId: '686400914700',
    projectId: 'push-notification-f9d37',
    authDomain: 'push-notification-f9d37.firebaseapp.com',
    storageBucket: 'push-notification-f9d37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBObZe1Pz4XjMEwxgcl9ZXWRacxtV97cfE',
    appId: '1:686400914700:android:a8befa901dd6b77a6cf529',
    messagingSenderId: '686400914700',
    projectId: 'push-notification-f9d37',
    storageBucket: 'push-notification-f9d37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxoLMv2e16EMEQvDeot41G90T7YYW7mUc',
    appId: '1:686400914700:ios:5960139c376d0f586cf529',
    messagingSenderId: '686400914700',
    projectId: 'push-notification-f9d37',
    storageBucket: 'push-notification-f9d37.appspot.com',
    iosBundleId: 'com.example.flutterPushNotif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxoLMv2e16EMEQvDeot41G90T7YYW7mUc',
    appId: '1:686400914700:ios:5960139c376d0f586cf529',
    messagingSenderId: '686400914700',
    projectId: 'push-notification-f9d37',
    storageBucket: 'push-notification-f9d37.appspot.com',
    iosBundleId: 'com.example.flutterPushNotif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOB_bgsxTWJKQ1sL4s-Ui-RgN4M4qvYlM',
    appId: '1:686400914700:web:3e07c318b8a1fcc26cf529',
    messagingSenderId: '686400914700',
    projectId: 'push-notification-f9d37',
    authDomain: 'push-notification-f9d37.firebaseapp.com',
    storageBucket: 'push-notification-f9d37.appspot.com',
  );
}
